name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Install Google SDK
        run: sudo apt-get update && sudo apt-get install -y google-cloud-sdk-pubsub-emulator

      - name: Start pubsub emulator
        run: |
          gcloud beta emulators pubsub start --host-port=localhost:8085 &
          sleep 5

      - name: Export environments variables to emulator
        run: |
          echo "PUBSUB_EMULATOR_HOST=localhost:8085" >> $GITHUB_ENV

      - name: Run tests
        run: make test-ci
        env:
          PUBSUB_EMULATOR_HOST: ${{ env.PUBSUB_EMULATOR_HOST }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
