name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instala Poetry
        run: pip install poetry

      - name: Instala dependências
        run: poetry install

      - name: Inicia emulador Pub/Sub
        run: |
          gcloud components install beta --quiet
          gcloud beta emulators pubsub start --host-port=localhost:8085 &
          sleep 5

      - name: Executa testes
        run: poetry run pytest --cov=src --cov-report=xml
